---
# Copyright (c) 2021 Orange
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
- name: Create flavor {{ item.flavor_name }}
  openstack.cloud.compute_flavor:
    cloud: "{{ cloud_detail }}"
    state: present
    name: "{{ item.flavor_name }}"
    ram: "{{ item.flavor_ram }}"
    vcpus: "{{ item.flavor_vcpus }}"
    disk: "{{ item.flavor_disk }}"
    extra_specs:
      "{{ item.flavor_extra_specs }}"
  when: admin | bool
