---
# Copyright (c) 2021 Orange
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
- name: Create the port {{ item.port_name }}
  openstack.cloud.port:
    state: present
    cloud: "{{ lookup('file', 'clouds-user.yaml') | from_yaml }}"
    name: "{{ item.port_name }}"
    network: "{{ item.network_name }}"
    vnic_type: "{{ item.vnic_type }}"
    security_groups: "{{ item.security_groups }}"
    port_security_enabled: "{{ item.port_security }}"
    fixed_ips:
      - subnet_id: "{{ subnet_ids[item.network_name] }}"
    validate_certs: "{{ validate_certs }}"
  register: port

- name: Add {{ item.port_name }} port name to server ports list
  set_fact:
    ports: "{{ ports | default([]) + ['port-name=' + item.port_name] }}"

- name: Add {{ item.port_name }} port information to data ports list
  set_fact:
    data_ports: "{{ data_ports | default([]) +
     [{'port_name': item.port_name, 'mac_address':port.port.mac_address,
      'vnic_type': item.vnic_type, 'topology': item.topology }] }}"
  when: port.port['binding:vnic_type'] != 'normal'

- name: Add {{ item.port_name }} port information to management ports list
  set_fact:
    mgmt_port: "{{ {'network_name': item.network_name, 'mac_address':port.port.mac_address, 'ip_address': port.port.fixed_ips[0].ip_address} }}"
  when: port.port['binding:vnic_type'] == 'normal'
