---
# Copyright (c) 2021 Orange
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0

- name: Create flavors for NFVbench traffic generator and loop VMs
  ansible.builtin.include_tasks: create_flavor.yml
  with_items: "{{ flavors }}"
  when: admin | bool

- name: Create security group for the management ports of the VMs
  ansible.builtin.include_tasks: security_group.yml
  when:
    - security_group_name is defined
    - security_group_name

- name: Create management networks for the traffic generator and loop VMs
  ansible.builtin.include_tasks: create_management_network.yml
  with_items: "{{ management_networks }}"
  when: management_networks is defined

- name: Create subnets for the management networks
  ansible.builtin.include_tasks: create_subnet.yml
  with_items: "{{ management_networks }}"
  when: management_networks is defined

- name: Create management ports
  ansible.builtin.include_tasks: create_port.yml
  with_items: "{{ management_networks }}"
  when: item.port_name is defined

- name: Create networks for the loop VM
  ansible.builtin.include_tasks: create_loopvm_network.yml
  with_items: "{{ loop_vm_networks }}"
  when: loop_vm_networks is defined

- name: Create subnets for the loop VM
  ansible.builtin.include_tasks: create_subnet.yml
  with_items: "{{ loop_vm_networks }}"
  when: loop_vm_networks is defined

- name: Filter e2e generator networks
  ansible.builtin.set_fact:
    generator_networks_e2e: "{{ generator_networks_e2e | default([]) + [item] }}"
  with_items: "{{ generator_networks }}"
  when:
    - item.topology is defined
    - item.topology == 'e2e' or item.topology == 'loopback_e2e'

- name: Create networks for the traffic generator VM (e2e case)
  ansible.builtin.include_tasks: create_generator_network.yml
  with_together:
    - "{{ generator_networks_e2e }}"
    - "{{ e2e_vlans }}"
  when: generator_networks_e2e is defined

- name: Filter loopback generator networks
  ansible.builtin.set_fact:
    generator_networks_loopback: "{{ generator_networks_loopback | default([]) + [item] }}"
  with_items: "{{ generator_networks }}"
  when:
    - item.topology is defined
    - item.topology == 'loopback'

- name: Create networks for the traffic generator VM (loopback case)
  ansible.builtin.include_tasks: create_generator_network.yml
  with_together:
    - "{{ generator_networks_loopback }}"
    - "{{ loopback_vlans }}"
  when: generator_networks_loopback is defined

- name: Create subnets for the traffic generator VM
  ansible.builtin.include_tasks: create_subnet.yml
  with_items: "{{ generator_networks }}"

- name: Create data ports for the traffic generator VM
  ansible.builtin.include_tasks: create_port.yml
  with_items: "{{ generator_networks }}"

- name: Create a virtual router between the management network(s) and the external network
  ansible.builtin.include_tasks: create_router.yml

- name: Create nfvbench config files for loopback and e2e scenarios
  ansible.builtin.include_tasks: create_config.yml

- name: Upload traffic generator and loop VM images
  ansible.builtin.include_tasks: upload_image.yml

- name: Create traffic generator VM
  ansible.builtin.include_tasks: create_server.yml
