---
# Copyright (c) 2021 Orange
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
- name: Check if clouds.yaml file exists
  stat:
    path: "clouds.yaml"
  register: clouds_result
  no_log: true

- name: Extract clouds.yaml vars
  set_fact:
    cloud_data: "{{ lookup('file', 'clouds.yaml') | from_yaml  }}"
  no_log: true

- name: Get project info from openstack API
  openstack.cloud.project_info:
    cloud: "{{ cloud_detail }}"
    name: "{{ project_name }}"
  register: openstack_project_info
  when:
    - admin | bool
    - not deploy | bool
    - project_id is not defined

- name: Extract project id from openstack API
  set_fact:
    project_id: "{{ openstack_project_info.openstack_projects[0].id }}"
  when:
    - admin | bool
    - not deploy | bool
    - project_id is not defined

- name: Extract project_id from clouds.yaml
  set_fact:
    project_id: "{{ cloud_data.clouds[cloud_detail].auth.project_id }}"
  when:
    - not admin | bool
    - project_id is not defined

- name: Set openstack variables as Ansible facts from clouds.yaml file
  set_fact:
    OS_AUTH_URL: "{{ cloud_data.clouds[cloud_detail].auth.auth_url }}"
    OS_PROJECT_ID: "{{ project_id }}"
    OS_PROJECT_NAME: "{{ project_name }}"
    OS_USER_DOMAIN_NAME: "{{ user_domain_name }}"
    OS_USERNAME: "{{ username }}"
    OS_PASSWORD: "{{ password }}"
    OS_REGION_NAME: "{{ cloud_data.clouds[cloud_detail].region_name }}"
    OS_PROJECT_DOMAIN_NAME: "{{ project_domain_name }}"
  no_log: true

- name: Generate clouds.yaml file for NFVbench generator VM
  template:
    src: clouds-nfvbench.yaml.j2
    dest: clouds-nfvbench.yaml
    mode: '0644'
  no_log: true

- name: Set CACERT env variable
  set_fact:
    OS_CACERT: "{{ cloud_data.clouds[cloud_detail].cacert }}"
  ignore_errors: true
  no_log: true

- name: Generate clouds-user.yaml file for current user
  template:
    src: clouds.yaml.j2
    dest: clouds-user.yaml
    mode: '0644'
  no_log: true
