---
# Copyright (c) 2021 Orange
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
- name: Run NFVbench role
  block:
    - name: Register NFVbench VNIC type from env
      set_fact:
        nfvbench_network_vnic_type: "{{ lookup('env', 'NFVBENCH_NETWORK_VNIC_TYPE') | default('direct', True) }}"

    - name: Check if a NFVbench template vars file exists
      stat:
        path: "{{ lookup('env', 'extra_vars') }}.j2"
      register: extra_vars_template
      ignore_errors: true
      no_log: true

    - name: Create NFVbench vars file
      template:
        src: "{{ lookup('env', 'extra_vars') }}.j2"
        dest: "{{ lookup('env', 'extra_vars') }}"
        mode: '0644'
      when:
        - extra_vars_template.stat.exists
      no_log: true

    - name: Check if NFVbench vars file exists
      stat:
        path: "{{ lookup('env', 'extra_vars') }}"
      register: extra_vars
      ignore_errors: true
      no_log: true

    - name: Load extra_vars
      include_vars: "{{ lookup('env', 'extra_vars') }}"
      when:
        - extra_vars.stat.exists
      no_log: true

    - name: Authenticate to the OpenStack cloud
      # Early test of OpenStack API availability
      openstack.cloud.auth:
        cloud: "{{ cloud_detail }}"
        validate_certs: "{{ validate_certs }}"
      no_log: true

    - name: Check user is admin
      # We check the user is admin by trying to list users, which is an
      # operation that requires admin rights.
      openstack.cloud.identity_user_info:
        cloud: "{{ cloud_detail }}"
        validate_certs: "{{ validate_certs }}"
      register: user_info
      ignore_errors: true
      no_log: true
      when: admin | bool

    - name: Clear admin variable
      set_fact:
        admin: False
      when:
        - admin | bool
        - user_info is failed

    - name: Create NFVbench project and user
      include_tasks: create_tenant.yml
      when: deploy | bool

    - name: Generate clouds.yaml files for NFVbench user in NFVbench project
      include_tasks: generate_user_creds.yml

    - name: Create flavors for NFVbench traffic generator and loop VMs
      include_tasks: create_flavor.yml
      with_items: "{{ flavors }}"
      when:
        - admin | bool
        - deploy | bool

    - name: Create security group for the management ports of the VMs
      include_tasks: security_group.yml
      when:
        - deploy | bool
        - security_group_name is defined
        - security_group_name

    - name: Create management networks for the traffic generator and loop VMs
      include_tasks: create_management_network.yml
      with_items: "{{ management_networks }}"
      when:
        - deploy | bool
        - management_networks is defined

    - name: Create subnets for the management networks
      include_tasks: create_subnet.yml
      with_items: "{{ management_networks }}"
      when:
        - deploy | bool
        - management_networks is defined

    - name: Create management ports
      include_tasks: create_port.yml
      with_items: "{{ management_networks }}"
      when:
        - deploy | bool
        - item.port_name is defined

    - name: Create networks for the loop VM
      include_tasks: create_loopvm_network.yml
      with_items: "{{ loop_vm_networks }}"
      when:
        - deploy | bool
        - loop_vm_networks is defined

    - name: Create subnets for the loop VM
      include_tasks: create_subnet.yml
      with_items: "{{ loop_vm_networks }}"
      when:
        - deploy | bool
        - loop_vm_networks is defined

    - name: Filter e2e generator networks
      set_fact:
        generator_networks_e2e: "{{ generator_networks_e2e | default([]) + [item] }}"
      with_items: "{{ generator_networks }}"
      when:
        - deploy | bool
        - item.topology is defined
        - item.topology == 'e2e' or item.topology == 'loopback_e2e'

    - name: Create networks for the traffic generator VM (e2e case)
      include_tasks: create_generator_network.yml
      with_together:
        - "{{ generator_networks_e2e }}"
        - "{{ e2e_vlans }}"
      when:
        - deploy | bool
        - generator_networks_e2e is defined

    - name: Filter loopback generator networks
      set_fact:
        generator_networks_loopback: "{{ generator_networks_loopback | default([]) + [item] }}"
      with_items: "{{ generator_networks }}"
      when:
        - deploy | bool
        - item.topology is defined
        - item.topology == 'loopback'

    - name: Create networks for the traffic generator VM (loopback case)
      include_tasks: create_generator_network.yml
      with_together:
        - "{{ generator_networks_loopback }}"
        - "{{ loopback_vlans }}"
      when:
        - deploy | bool
        - generator_networks_loopback is defined

    - name: Create subnets for the traffic generator VM
      include_tasks: create_subnet.yml
      with_items: "{{ generator_networks }}"
      when: deploy | bool

    - name: Create data ports for the traffic generator VM
      include_tasks: create_port.yml
      with_items: "{{ generator_networks }}"
      when: deploy | bool

    - name: Create a virtual router between the management network(s) and the external network
      include_tasks: create_router.yml
      when: deploy | bool

    - name: Create nfvbench config files for loopback and e2e scenarios
      include_tasks: create_config.yml
      when: deploy | bool

    - name: Upload traffic generator and loop VM images
      include_tasks: upload_image.yml
      when: deploy | bool

    - name: Create traffic generator VM
      include_tasks: create_server.yml
      when: deploy | bool

    - name: Check SSH and HTTP connectivity with the traffic generator VM
      include_tasks: healthcheck.yml
      when: deploy | bool or run_test | bool

    - name: Restart nfvbench and run Xtesting test case
      include_tasks: run_test.yml
      when: run_test | bool

  always:
    - name: Delete the OpenStack resources created by ansible-role-nfvbench
      include_tasks: cleanup.yml
      when: cleanup | bool
