---
# Copyright (c) 2021 Orange
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0

- name: Run NFVbench role
  block:
    - name: Read role configuration and check OpenStack API
      include_tasks: prepare.yml

    - name: Create NFVbench project and user
      include_tasks: create_tenant.yml
      when:
        - admin | bool
        - deploy | bool

    - name: Generate clouds.yaml files for NFVbench user in NFVbench project
      include_tasks: generate_user_creds.yml

    - name: Deploy traffic generator VM
      include_tasks: deploy_tgen.yml
      when: deploy | bool

    - name: Check SSH and HTTP connectivity with the traffic generator VM
      include_tasks: healthcheck.yml
      when: deploy | bool or run_test | bool

    - name: Restart nfvbench and run Xtesting test case
      include_tasks: run_test.yml
      when: run_test | bool

  always:
    - name: Delete the OpenStack resources created by ansible-role-nfvbench
      include_tasks: cleanup.yml
      when: cleanup | bool
